name: Update Last DP Badge

on:
  push:
    branches: [main]
    paths: ['data/**']
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Calculate time since last DP change
        id: calc_time
        run: |
          if [ -f "data/last_run.txt" ]; then
            last_run=$(cat data/last_run.txt)
            current_time=$(date +%s)
            time_diff=$((current_time - last_run))
            
            hours=$((time_diff / 3600))
            minutes=$(((time_diff % 3600) / 60))
            
            if [ $hours -gt 0 ]; then
              if [ $hours -eq 1 ]; then
                time_text="${hours}h ${minutes}m ago"
              else
                time_text="${hours}h ${minutes}m ago"
              fi
            else
              if [ $minutes -eq 0 ]; then
                time_text="just now"
              elif [ $minutes -eq 1 ]; then
                time_text="1 min ago"
              else
                time_text="${minutes} mins ago"
              fi
            fi
            
            echo "time_text=$time_text" >> $GITHUB_OUTPUT
          else
            echo "time_text=never" >> $GITHUB_OUTPUT
          fi
          
      - name: Create custom badge
        run: |
          mkdir -p .github/badges
          
          # URL encode the time text
          time_encoded=$(echo "${{ steps.calc_time.outputs.time_text }}" | sed 's/ /%20/g')
          
          # Create badge URL
          badge_url="https://img.shields.io/badge/Last%20DP%20Change-${time_encoded}-green?style=flat-square"
          
          # Save badge info
          echo "$badge_url" > .github/badges/last-dp-change.txt
          echo "${{ steps.calc_time.outputs.time_text }}" > .github/badges/last-dp-time.txt
          
      - name: Commit badge update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .github/badges/
          git commit -m "Update last DP change badge [skip ci]" || echo "No changes to commit"
          git push
